version: '3.6'

services:
  serve:
    image: docker.pkg.github.com/smu-heartcode/heartcode.app/serve:${TAG}
    build: serve
    ports:
      - "80:80"
      - "443:443"
    environment:
      WEB_URL: web:3000
      API_URL: api:4000
    volumes:
      - var-www:/var/www
      - caddy_data:/data

  web:
    image: docker.pkg.github.com/smu-heartcode/heartcode.app/web:${TAG}
    build: web

  api:
    image: docker.pkg.github.com/smu-heartcode/heartcode.app/api:${TAG}
    build: api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_TOKEN: ${AUTH_TOKEN}
    volumes:
      - var-www:/var/www

  postgres:
    image: postgres:12
    ports:
      - "35432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  var-www:
  caddy_data:
