version: '3.6'

services:
  serve:
    image: docker.pkg.github.com/smu-heartcode/heartcode-app/serve:${TAG}
    restart: unless-stopped
    build: serve
    ports:
      - "80:80"
      - "443:443"
    environment:
      WEB_URL: web:3000
      API_URL: api:4000
      CLOUDFLARE_AUTH_TOKEN: ${CLOUDFLARE_AUTH_TOKEN}
    volumes:
      - var-www:/var/www
      - caddy_data:/data

  web:
    image: docker.pkg.github.com/smu-heartcode/heartcode-app/web:${TAG}
    restart: unless-stopped
    build: web

  api:
    image: docker.pkg.github.com/smu-heartcode/heartcode-app/api:${TAG}
    restart: unless-stopped
    build: api
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      VAR_WWW: /var/www
    volumes:
      - var-www:/var/www

volumes:
  var-www:
  caddy_data:
