version: '3.6'

services:
  serve:
    image: docker.pkg.github.com/smu-heartcode/heartcode.app/serve:latest
    build: serve
    ports:
      - "80:80"
    environment:
      WEB_URL: http://web:3000
      API_URL: http://api:4000
    volumes:
      - var-www:/var/www

  web:
    image: docker.pkg.github.com/smu-heartcode/heartcode.app/web:latest
    build: web

  api:
    image: docker.pkg.github.com/smu-heartcode/heartcode.app/api:latest
    build: api
    environment:
      DATABASE_URL: postgres://heartcode-app:eye-gas-ewe-put-something-secure-hear@postgres:5432/heartcode-app
      AUTH_TOKEN: eye-gas-ewe-put-something-secure-hear
    volumes:
      - var-www:/var/www

  postgres:
    image: postgres:12
    ports:
      - "35432:5432"
    environment:
      POSTGRES_DB: heartcode-app
      POSTGRES_USER: heartcode-app
      POSTGRES_PASSWORD: eye-gas-ewe-put-something-secure-hear

volumes:
  var-www:
