name: "Branch"

on:
  - push

jobs:
  rule:
    name: Branch Rule
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([a-z])+'
          allowed_prefixes: 'feature,feat,enhancement,fix,bug,bugfix,chore,docs'
          ignore: master
